### PR TITLE
Added construx-makara dependencies

### LINKED ISSUE #211: makara/browserify combination does not install construx-makara-browserify

### PR DESCRIPTION
**Pull request by aravindsrivats**
Fixes #211

### CODE REVIEW

**Comment by gabrielcsapo** [comment]
@grawk looks like a valid add, the tests fail on 0.12 which I don't think we need to support any longer.

**Comment by grawk** [comment]
Agreed. Wow, March 26th... really should keep an eye on these repos :eyes:

**Comment by gabrielcsapo** [comment]
going to merge 😄

**Comment by grawk** [comment]
prior to publishing we should test this new scenario locally @gabrielcsapo

**Comment by grawk** [comment]
Thanks for taking a look at this old PR @gabrielcsapo

**Comment by gabrielcsapo** [comment]
I am working on updating the repo to use a newer version of `yeoman`

**Pull request merged**
